/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 63927
 */
public class OrderSystem extends javax.swing.JFrame {

    /**
     * Creates new form OrderSystem
     */
    public OrderSystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        alltotal = new javax.swing.JTextField();
        fries = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        payment = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        atlast = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        shake = new javax.swing.JTextField();
        resultone = new javax.swing.JTextField();
        resultthree = new javax.swing.JTextField();
        resulttwo = new javax.swing.JTextField();
        burger = new javax.swing.JTextField();
        background1 = new javax.swing.JLabel();
        background2 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tel. No. 349 - 7530");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(360, 50, 110, 60);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("BURGER");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(290, 140, 70, 40);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("For feedback and inquiries ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(100, 430, 150, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("E.Sabellano St. Sto.Nino, Cebu City");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(320, 10, 230, 60);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ZAYA'S BURGER, FRIES & SHAKE");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(310, 0, 230, 40);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CHANGE");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(370, 300, 70, 40);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("QUANTITY");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(370, 110, 80, 40);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("OFFICIAL RECEIPT");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(360, 80, 130, 40);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("SHAKE");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(290, 200, 70, 40);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("FRIES");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(290, 170, 70, 40);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("PRODUCT");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(290, 110, 70, 40);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("SUB TOTAL");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(460, 110, 90, 40);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Cellphone No. 0927 - 616 - 4832");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(320, 30, 190, 60);

        jButton1.setText("ORDER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(290, 250, 72, 23);

        alltotal.setEditable(false);
        alltotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        alltotal.setText("0");
        jPanel1.add(alltotal);
        alltotal.setBounds(460, 250, 64, 22);
        jPanel1.add(fries);
        fries.setBounds(370, 180, 64, 22);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("\"The only thing we love more than food is you!\"");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(40, 470, 270, 30);
        jPanel1.add(payment);
        payment.setBounds(460, 280, 64, 22);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("TOTAL");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(380, 240, 60, 40);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("PAYMENT");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(370, 270, 70, 40);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Thank you!");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(150, 410, 70, 30);

        atlast.setEditable(false);
        atlast.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        atlast.setText("0");
        jPanel1.add(atlast);
        atlast.setBounds(460, 310, 64, 22);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("please call 349 - 7530 / 0927 - 616 - 4832");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(60, 450, 260, 30);
        jPanel1.add(shake);
        shake.setBounds(370, 210, 64, 22);

        resultone.setEditable(false);
        resultone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        resultone.setText("0");
        jPanel1.add(resultone);
        resultone.setBounds(460, 150, 64, 22);

        resultthree.setEditable(false);
        resultthree.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        resultthree.setText("0");
        jPanel1.add(resultthree);
        resultthree.setBounds(460, 210, 64, 22);

        resulttwo.setEditable(false);
        resulttwo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        resulttwo.setText("0");
        jPanel1.add(resulttwo);
        resulttwo.setBounds(460, 180, 64, 22);
        jPanel1.add(burger);
        burger.setBounds(370, 150, 64, 22);

        background1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Zayamenu.png"))); // NOI18N
        jPanel1.add(background1);
        background1.setBounds(0, 0, 280, 400);

        background2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.jpg"))); // NOI18N
        jPanel1.add(background2);
        background2.setBounds(280, 0, 270, 400);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("TOTAL");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(380, 240, 60, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/footer.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 400, 550, 120);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int itemburger = Integer.parseInt(burger.getText());
        int itemfries = Integer.parseInt(fries.getText());
        int itemshake = Integer.parseInt(shake.getText());
        
        int money = Integer.parseInt(payment.getText());
        
        int valueone = itemburger * 35;
        int valuetwo = itemfries * 15;
        int valuethree = itemshake * 15;
   
        int total = valueone + valuetwo + valuethree;
        int last = money - total;
        
        resultone.setText(""+valueone);
        resulttwo.setText(""+valuetwo);
        resultthree.setText(""+valuethree);
        alltotal.setText(""+total);
        atlast.setText(""+last);
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alltotal;
    private javax.swing.JTextField atlast;
    private javax.swing.JLabel background1;
    private javax.swing.JLabel background2;
    private javax.swing.JTextField burger;
    private javax.swing.JTextField fries;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField payment;
    private javax.swing.JTextField resultone;
    private javax.swing.JTextField resultthree;
    private javax.swing.JTextField resulttwo;
    private javax.swing.JTextField shake;
    // End of variables declaration//GEN-END:variables
}
